### PR TITLE
fixed markdown typos

### PR DESCRIPTION
**Pull request by entrptaher**

### CODE REVIEW

**Comment by danielecr** [comment]
I do not think it is a typo, or at least "update xxx" are not intended as same level of of Nodeshop: at least h2. so ## would be better.

**Comment by entrptaher** [comment]
Well it does not show things properly. So it was a typo in my view.
image

Peace.

**Comment by danielecr** [comment]
hash (#) is a proper sign. I am not the author, mine is just a comment

**Comment by entrptaher** [comment]
I'm removing the commits since I don't think it's going to be updated any soon.

**Pull request closed without merging**
